### ISSUE TITLE
Add title to table header seems doesn't work.

### ISSUE THREAD

**Issue by thomasyuan** [dpilch/solmd#10]
Update to solmd 1.6, but in generated document, there is still no title on table header.
I guess we need to update the lib/template.js as well?

I tried to update that one, but pre-commit hook blocks me.

**Comment by thomasyuan** [comment]
ping @dpilch

**Comment by dpilch** [comment]
Sorry, I've been busy. I'll look at this soon.

**Comment by JirkaChadima** [comment]
It actually can't be compiled at all after a0bc55209. When I delete https://github.com/dpilch/solmd/commit/a0bc55209b785337ccaed326c5937123cd7fe0af#diff-eed64a56d9b95461323a66cae6d2380bR28 it works as expected. Well, the tests fail as expected.
